# Generated by Django 4.1.5 on 2023-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
