# Generated by Django 4.1.5 on 2023-03-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='key',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='backend.key'),
        ),
    ]
