# Generated by Django 4.1.5 on 2023-03-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
